### PR TITLE
NH compat, cleanup, remove unused nh save data

### PR DESCRIPTION
**Pull request by xen-42**
- The Outsider is now compatible with NH (will de-activate when NH loads a new star system, and will not conflict with main menu changes)
- When The Outsider copied bug fixes from NH it also copied over NH achievements, removed that since it is unneeded

Only other change that is required is a PR to the main Outsider repo to remove NH from the mod conflicts list

Some changes to NH must be merged first, so this will happen after https://github.com/Outer-Wilds-New-Horizons/new-horizons/pull/805 is merged

### CODE REVIEW

**Comment by TRSasasusu** [comment]
Thank you for making NH compatible PR! It would be very helpful for people running the vision and the outsider in the same time ::)

But, ... please, please remove unnecessary diffs due to formatting (i.e., diffs about spaces -> tabs, `() {\n` -> `()\n{`, ...)

And, what is `libs/TheOutsider.dll`? Could it be generated by GitHub Actions? (I would like to generate dll files by GitHub Actions in terms of authenticity.)

**Comment by xen-42** [comment]
but the new formatting looks better! At least doing `()\n{` is the C# convention and `() {\n` is technically incorrect, but I'll look into fixing the spaces to tabs

TheOutsider.dll is the dll of the original mod and its required to patch it. It's included in the repo so that the github action can run. I think it's possible to check out the release of the original mod in an action and grab the dll but that would be really complicated for no real gain, especially since the original is abandoned and will not be updated anymore. That dll does not end up getting included in the release, its just to allow the action to run

**Comment by xen-42** [comment]
Fixed the spaces

**Comment by TRSasasusu** [comment]
>TheOutsider.dll is the dll of the original mod and its required to patch it. It's included in the repo so that the github action can run.

Are you meaning integrating this mod and the outsider (this mod into the outsider / the outsider into this mod)?

Anyway, I am looking at https://github.com/StreetlightsBehindTheTrees/Outer-Wilds-The-Outsider/pull/12 and https://github.com/Outer-Wilds-New-Horizons/new-horizons/pull/805 .

(And, I'm curious why did you move `Harmony.CreateAndPatchAll(Assembly.GetExecutingAssembly());` from `Awake()` to `Start()`.)

**Comment by xen-42** [comment]
Hmm yeah I think it was because I was trying to debug the patches not working, but in the end I was just doing it wrong. I'll move it back to awake. But yes, this mod will just be merged into the Outsider so I'm going to close this PR

**Pull request closed without merging**
